// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://laldnkchpksjsqxilokp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhbGRua2NocGtzanNxeGlsb2twIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjA2MTQsImV4cCI6MjA3MDIzNjYxNH0._jgsTCgWlotzeMiqdFQTySD_UNarUJk1Ja3u_MwPfP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});